name: release
on:
  push:
    tags:
      - "**"
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history 
          fetch-depth: 0
      - name: Maven Publish
        id: maven_publish
        env:
          MAVEN_USERNAME: ${{ secrets.BINTYRAY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.BINTYRAY_PASSWORD }}
        run: |
          chmod 777 ./gradlew
          ./gradlew bintrayUpload